
# Variable Definitions
variables:
    VADERE_DEPLOYMENT_BASE_URL: "http://www.vadere.org/builds"
    VADERE_PACKAGE_NAME_BRANCHES: "vadere.${CI_COMMIT_REF_NAME}.${CI_RUNNER_TAGS}.zip"
    VADERE_PACKAGE_NAME_RELEASES: "vadere.${CI_COMMIT_TAG}.${CI_RUNNER_TAGS}.zip"
    EIKMESH_PACKAGE_NAME_BRANCHES: "eikmesh.${CI_COMMIT_REF_NAME}.${CI_RUNNER_TAGS}.zip"


# Stage Definitions
stages:
    - build
    - unit_test
    - seed_test
    - deploy
    
    
# Job Template Definitions
.builds:
    stage: build
    script:
        - echo "Setup enviroment"
        - virtualenv --system-site-packages -p python3.8 ./venv
        - source venv/bin/activate
        - python3 -m pip install --upgrade pip
        - python3 -m pip install --upgrade setuptools
        - pip3 install -q -I -r requirements.txt
        - pip3 list
        - echo "finished setting up the enviroment"
    artifacts:
        when: always
        paths:
            - "*/target/coverage-reports"
        expire_in: 1 week
    when: always
            
.template_unit_test:
    stage: unit_test
    script:
        - python3 -m unittest discover -v
        - python3 --version
        - pip3 list
    artifacts:
        when: on_failure
        paths:
            - "vadere_logs"
        expire_in: 1 week
    when: on_success


# Job Definitions

## Jobs for GNU/Linux runner (which is labeled with tag "linux")
build_env_on_linux:
    extends: .builds
    tags:
        - linux

run_unit_tests_on_linux:
    extends: .template_unit_test
    tags:
        - linux
